
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Infrastructure.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Informacion
{

    public int Id { get; set; }

    public string Texto { get; set; }

    public byte[] Doc1 { get; set; }

    public int TipoInformacion { get; set; }

    public bool Borrado { get; set; }



    public virtual TipoInformacion TipoInformacion1 { get; set; }

}

}
