//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Residencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Residencia()
        {
            this.Deuda = new HashSet<Deuda>();
        }
    
        public int Id { get; set; }
        public int Propietario { get; set; }
        public byte Habitantes { get; set; }
        public Nullable<System.DateTime> AnioConstrucion { get; set; }
        public int Condicion { get; set; }
        public byte Vehiculos { get; set; }
        public Nullable<bool> Borrado { get; set; }
        public string Descripcion { get; set; }
    
        public virtual CondicionResidencia CondicionResidencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deuda> Deuda { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
