
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Infrastructure.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    [MetadataType(typeof(UsuarioMetadata))]
public partial class Usuario
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Usuario()
    {

        this.Incidente = new HashSet<Incidente>();

        this.Reservacion = new HashSet<Reservacion>();

        this.Residencia = new HashSet<Residencia>();

    }


    public int Id { get; set; }

    public int IdTipoUsuario { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public int Cedula { get; set; }

    public string Email { get; set; }

    public string Contrasenna { get; set; }

    public bool Borrado { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Incidente> Incidente { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Reservacion> Reservacion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Residencia> Residencia { get; set; }

    public virtual TipoUsuario TipoUsuario { get; set; }

}

}
